import { createMessage, storeMessage } from "./modules/utils";
import { initializeApp } from "./app";
import { auth } from "./firebase";
import { navigateTo } from "./modules/navigate";
import i18n from './i18n';

/* I have taken the Google form the Solon team was using and used this tool: https://stefano.brilli.me/google-forms-html-exporter/
to extract the form elements and  code to submit the form. The input names are generated by Google and can not be changed */
const mailingListForm = document.getElementById(
  "mailingList",
) as HTMLFormElement;

function submitData() {
  //Create submitting data message
  createMessage(i18n.t('event_sumbitting'), "main-message", "info");
  const mailingFormData: FormData = new FormData(mailingListForm);

  //Validate full name input
  const fullNameValue = mailingFormData.get("entry.394076337");
  if (fullNameValue === null || fullNameValue.toString().trim() === "") {
    createMessage(i18n.t('event_name_error'), "main-message", "error");
    return;
  } else {
    const firstLastCheck = fullNameValue.toString().split(" ");
    if (firstLastCheck.length < 2) {
      createMessage(
        i18n.t('event_full_name_error'),
        "main-message",
        "error",
      );
      return;
    }
  }
  //Validate email
  const emailValue = mailingFormData.get("entry.1675960952");
  if (emailValue === null || emailValue.toString().trim() === "") {
    createMessage(i18n.t('event_email_error'), "main-message", "error");
    return;
  }
  const checkForAtSymbol = emailValue.toString().split("@");
  if (checkForAtSymbol.length < 2) {
    createMessage(i18n.t('event_valid_email_error'), "main-message", "error");
    return;
  }
  //Validate phone if entered
  const phoneValue = mailingFormData.get("entry.889580350");
  if (phoneValue !== null && phoneValue.toString().replace(/\D/g, "") !== "") {
    const parsedPhone: number = parseInt(
      phoneValue.toString().replace(/\D/g, ""),
    );
    if (isNaN(parsedPhone)) {
      createMessage(
        i18n.t('valid_phone_error'),
        "main-message",
        "error",
      );
      return;
    } else {
      const lengthCheck: number = String(Math.abs(parsedPhone)).length;
      if (lengthCheck < 10 || lengthCheck > 11) {
        createMessage(
          i18n.t('valid_phone_error'),
          "main-message",
          "error",
        );
        return;
      }
    }
  }
  //Validate volunteer type
  const volunteerTypeValue = mailingFormData.get("entry.1085615321");
  if (volunteerTypeValue === null) {
    createMessage(
      i18n.t('email_type_error'),
      "main-message",
      "error",
    );
    return;
  }
  //Validate language
  const languageValue = mailingFormData.get("entry.562438076");
  if (languageValue === null) {
    createMessage(
      i18n.t('language_select_error'),
      "main-message",
      "error",
    );
    return;
  }
  //If there are no errors, send the form data to the form response spreadsheet.
  const formData: FormData = new FormData(mailingListForm);
  const formAction: string =
    "https://docs.google.com/forms/d/e/1FAIpQLScUgRwg1GxdTf4IaEfRwc2VwEIT3XSeOAezyInNmu1wyprS3Q/formResponse";
  fetch(formAction, {
    method: "POST",
    body: formData,
    mode: "no-cors",
  })
    .then((response) => {
      //Store the message to be displayed after redirected to the home page
      storeMessage(
        i18n.t('mailing_list_sucess'),
        "main-message",
        "check_circle",
      );
      navigateTo("/");
    })
    .catch((error) => {
      //Create an error message
      console.error("Network Error:", error);
      createMessage(
        i18n.t('mailing_sumbit_error'),
        "main-message",
        "error",
      );
    });
}

initializeApp("Mailing List", "Mailing List").then(() => {
  //If the user is signed in, populate the input fields with the user's info
  auth.onAuthStateChanged((user) => {
    if (user) {
      const fullNameInput = document.getElementById(
        "fullNameInput",
      ) as HTMLFormElement;
      fullNameInput.value = user.displayName;
      const emailInput = document.getElementById(
        "emailInput",
      ) as HTMLFormElement;
      emailInput.value = user.email;
      //Not populating phoneNumberInput since the field is optional
    }
  });
});

mailingListForm.addEventListener("submit", (e) => {
  e.preventDefault();
  submitData();
});
